#!/usr/bin/expect -f
# Expect script to connect to a remote server and execute command.
# This script needs two part arguments :
# part I
#     password = Password of username the remote server.
# part II
#     command = you will execute command in the remote server.
# example:
## non-interactive ssh
#     ./rsh password ssh root@192.168.1.1
#     ./rsh password ssh -p 2222 root@192.168.1.1
## non-interactive scp
#     ./rsh password scp root@192.168.1.1:/tmp/test .
#     ./rsh password scp root@192.168.1.1:/tmp/test /tmp/test
#     ./rsh password scp /tmp/test root@192.168.1.1:/tmp/test
#     ./rsh password scp -P 2222 root@192.168.1.1:/tmp/test .
## non-interactive execute command on the remote server.
#     ./rsh password ssh -p 2222 root@192.168.1.1 df -h
#     ./rsh password ssh -p 2222 root@192.168.1.1 free -m
#     ./rsh password ssh -p 2222 root@192.168.1.1 mv -f file1 file2
#     ./rsh password ssh -p 2222 root@192.168.1.1 cp -f file1 file2


 if {[llength $argv] < 3} {
     puts "usage: exp password command"
     exit 1
 }

set timeout 20

set password [lindex $argv 0]
set cmd [lrange $argv 1 end]

eval spawn $cmd
expect {
     -re "yes/no" {
        send "yes\r";
    } -re "assword:" {
        send "$password\r";
    } timeout {
        exit
    } eof {
        exit
    }
}

interact
